apps/propaganda/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaPropagandas, 
	DetalleView,
	ActualizarView,
	CreatePropagandas,
	EliminarView
	)

urlpatterns = [

	url(r'^propagandas/$', ListaPropagandas.as_view(), name = 'lista_propagandas'),
	url(r'^propagandas/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_propaganda'),
	url(r'^propagandas/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_propaganda"),
	url(r'^propagandas/agregar$', CreatePropagandas.as_view(), name='crear_propaganda'),
	url(r'^propagandas/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_propaganda"), 
	]

sanbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings


# from apps.home.views import (
#     LandingView, HomeView,
#     ContactView, HelpView
#     )

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.inicio.urls',namespace='inicio')),
    
    url(r'^integrations/', include('apps.messenger.urls', namespace="integrations")),
    url(r'', include('apps.proveedor.urls',namespace='proveedor')),
    url(r'', include('apps.cliente.urls',namespace='clientes_app')),
    url(r'', include('apps.producto.urls',namespace='productos')),
    url(r'', include('apps.empleado.urls',namespace='empleados')),
    url(r'', include('apps.venta.urls',namespace='ventas')),
    url(r'', include('apps.repuesto.urls',namespace='repuestos')),
    url(r'', include('apps.propaganda.urls',namespace='propagandas')),


    # URL APPS PROJECT 

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),

]	

apps/propaganda/models.py
from django.db import models

from django.utils.translation import ugettext_lazy as _


class Propaganda(models.Model):
	
	nombre = models.CharField(
		max_length = 120,
		verbose_name = _('Nombre')
	)

	descripcion = models.TextField(
		verbose_name = _('Descripcion')
	)

	url = models.URLField(
		verbose_name = _('URL Propaganda'),
		max_length = 500
	)

	habilitado = models.BooleanField(
		default = True,
		verbose_name = _('Habilitado')
	)

	def __str__(self):
		return self.nombre


	class Meta:
		verbose_name = _('Propaganda')
		verbose_name_plural = _('Propagandas')

apps/propaganda/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from .models import Propaganda

class PropagandaForm(forms.ModelForm):
	class Meta:
		model = Propaganda
		fields = "__all__"

apps/propaganda/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .models import Propaganda
from .forms import PropagandaForm


# ListaPropagandas, 
# DetalleView,
# ActualizarView,
# CreatePropagandas,
# EliminarView


class ListaPropagandas(ListView):
	model = Propaganda
	context_object_name = 'lista_propagandas'
	template_name = 'propagandas/listar_propagandas.html'


class DetalleView(DetailView):
	model = Propaganda
	template_name = 'propagandas/detalle_propaganda.html'


class ActualizarView(UpdateView):
	form_class = PropagandaForm
	template_name = 'propagandas/update_propaganda.html'
	model = Propaganda
	success_url = '/propagandas'

class CreatePropagandas(CreateView):
	form_class = PropagandaForm
	template_name = 'propagandas/create_propaganda.html'
	model = Propaganda
	success_url = '/propagandas'


class EliminarView(DeleteView):
	model = Propaganda
	template_name = 'propagandas/eliminar_propaganda.html'
	success_url = '/propagandas'

templates/propagandas/create_propaganda.html
{% extends "base.html" %}
{% block title %}Propaganda{% endblock title %}

{# Load the tag library #}
{% load bootstrap3 %}

{% block content %}

<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Propaganda
          </h1>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post" autocomplete="off">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div id="forms" >
                                      {% bootstrap_form form %}
                                    </div>
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>             
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/propagandas/detalle_propaganda.html
{% extends "base.html" %}
{% block title %}Propaganda{% endblock title %}
{% block content %}
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
          
            <div class="box-header with-border">
          		<a href="{% url 'propagandas:lista_propagandas' %}" class="btn btn-success">
            		<span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>              
              		<div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->            
            </div><!-- /.box-header -->
              <div class="box-body">
                  <table class="table table-striped table table-hover ">
                        <thead>
                            <tr>
                             <th><h2> Propaganda: {{ object.nombre | capfirst }}</h2></th>           
                           </tr>
                        </thead>              
	                    <tbody> 
	                          <tr class="success"> 
	                          	  <td><strong>Nro:</strong></td>                           
	                              <td>{{ object.id }}</td>
	                          </tr>
	                          <tr class="success">
	                          	  <td><strong>Nombre:</strong></td>
	                              <td>{{ object.nombre }} </td> 
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Descripcion:</strong></td>
	                              <td>{{ object.descripcion }}</td>                              
	                           </tr>
	                           	<tr class="success">
	                           	  <td><strong>Url:</strong></td>
	                              <td>{{ object.url }}</td>                              
	                           </tr> 
	                           <tr class="success">
	                           	  <td><strong>Habilitado:</strong> </td>
	                           	  {% if object.habilitado == True %}
	                              	<td>Si</td>                  
	                              {% else %}
	                              	<td>No</td>                  
	                              {% endif %}
	                           </tr> 
	                    </tbody>
	               	</table>                                 
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/propagandas/eliminar_propaganda.html
{% extends "base.html" %}
{% block title %}Propaganda{% endblock title %}
{% block content %}
 
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar la propaganda "{{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'propagandas:lista_propagandas' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/propagandas/listar_propagandas.html
{% extends "base.html" %}
{% block title %}Propagandas{% endblock title %}

{% block css %}
<!-- DataTables -->
<link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
{% endblock css %}

{% block content %}
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Propagandas
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title"><a href="{% url 'propagandas:crear_propaganda' %}" class="btn btn-success">
                      Nuevo Propaganda
                    </a></h3>
                      {% if user.empleado.tipo == "Gerente" %}
                        <a  class="btn btn-primary pull-right" href="/clientes/reporte">imprimir</a>
                      {% endif %}
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Nombre</th> 
                        <th>Habilitado</th>
                        <th>Acciones</th>                       
                      </tr>
                    </thead>
                    <tbody>
                    
                     {% for propaganda in lista_propagandas %}          

                        <tr> 
                          <td>{{ forloop.counter }}</td>
                          <td>{{ propaganda.nombre }} </td> 
                          {% if propaganda.habilitado == True %}
                              <td> Si </td>
                          {% else %}
                              <td> No </td>
                          {% endif %}

                          <td class="text-right">
                                  <center><a href="{% url 'propagandas:detalle_propaganda' propaganda.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>

                                  <a href="{% url 'propagandas:actualizar_propaganda' propaganda.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                     {% if user.empleado.tipo == 'Gerente' %}
                                  <a href="{% url 'propagandas:eliminar_propaganda' propaganda.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></center></a> 
                                   {% endif %}
                            </td>                      
                              
                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% endblock content %}

{% block extrajs %}
<!-- DataTables -->
<script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>

<!-- SlimScroll -->
<script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/plugins/fastclick/fastclick.min.js"></script>

    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
       </script>

       
{% endblock extrajs %}

templates/propagandas/update_propaganda.html
{% extends "base.html" %}
{% block title %}Propaganda{% endblock title %}

{# Load the tag library #}
{% load bootstrap3 %}

{% block content %}

<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Propaganda
          </h1>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div id="forms">
                                      {% bootstrap_form form %}
                                    </div>
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>             
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}