apps/cliente/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaClientes, 
	DetalleView,
	ActualizarView,
	CreateClientes,
	EliminarView,
	generar_reporte_clientes
	)

urlpatterns = [

	url(r'^clientes/$', ListaClientes.as_view(), name = 'lista_clientes'),
	url(r'^clientes/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_cliente'),
	url(r'^clientes/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_cliente"),
	url(r'^clientes/agregar$', CreateClientes.as_view(), name='crear_cliente'),
	url(r'^clientes/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_cliente"), 
	url(r'^clientes/reporte/$', generar_reporte_clientes,name='reporte'),
	]

apps/empleado/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaEmpleados, 
	DetalleView,
	ActualizarView,
	CreateEmpleados,
	EliminarView,
	generar_reporte_empleados
	)

urlpatterns = [

	url(r'^empleados/$', ListaEmpleados.as_view(), name = 'lista_empleados'),
	url(r'^empleados/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_empleado'),
	url(r'^empleados/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_empleado"),
	url(r'^empleados/agregar$', CreateEmpleados.as_view(), name='crear_empleado'),
	url(r'^empleados/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_empleado"), 
	url(r'^empleados/reporte/$', generar_reporte_empleados,name='reporte'),
	]

sanbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings


# from apps.home.views import (
#     LandingView, HomeView,
#     ContactView, HelpView
#     )

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.inicio.urls',namespace='inicio')),
    
    url(r'^integrations/', include('apps.messenger.urls', namespace="integrations")),
    url(r'', include('apps.proveedor.urls',namespace='proveedor')),
    url(r'', include('apps.cliente.urls',namespace='clientes_app')),
    url(r'', include('apps.producto.urls',namespace='productos')),
    url(r'', include('apps.empleado.urls',namespace='empleados')),
    url(r'', include('apps.venta.urls',namespace='ventas')),
    url(r'', include('apps.repuesto.urls',namespace='repuestos')),
    url(r'', include('apps.propaganda.urls',namespace='propagandas')),


    # URL APPS PROJECT 

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),

]	

apps/empleado/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
		

VENDEDOR = 'Vendedor'
MECANICO = 'Mecanico'
GERENTE = 'Gerente'

tipo_choice = (
	(VENDEDOR, 'Vendedor'),
	(MECANICO, 'Mecanico'),
	(GERENTE, 'Gerente'),
 )

class Empleado(models.Model):
	
	empleado = models.OneToOneField(
        'users.User',
		verbose_name =('Usuario'),
		related_name='empleado',
	)

	cedula = models.CharField(
		verbose_name =_('cedula'),
		max_length=20,
		unique=True,
	)


	celular = models.CharField(
		verbose_name =_('Celular'),
		max_length=20
	)

	tipo = models.CharField(
		verbose_name=_('Tipo'),
		max_length=20, 
		choices=tipo_choice,
		default=VENDEDOR
	)

	habilitado = models.BooleanField(
		verbose_name =_('Habilitado'),
		default = True
	)

	imagen = models.ImageField(
		verbose_name =_('Imagen'),
		null=True,
		blank=True,
		upload_to = "imagenes/empleado"
	)

	thumbnail = ImageSpecField(
		source='imagen',
		processors=[ResizeToFill(100, 50)],
		format='JPEG',
		options={'quality': 60}
	)

	class Meta:
		ordering = ['cedula']
		verbose_name_plural = "Empleados"

	def __str__(self):
		return '%s -  %s' % (self.empleado.first_name, self.tipo)

apps/empleado/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
	class Meta:
		model = Empleado
		fields = "__all__"

apps/empleado/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from .models import Empleado
from .forms import EmpleadoForm

from datetime import *
import xhtml2pdf.pisa as pisa
from django import http
from django.template.loader import get_template
from django.template import Context
from io import BytesIO as StringIO
import cgi


class ListaEmpleados(ListView):
	model = Empleado
	context_object_name = 'lista_empleados'
	template_name = "empleados/lista_empleados.html"

class DetalleView(DetailView):
	model = Empleado
	template_name = 'empleados/detalle_empleados.html'

class ActualizarView(UpdateView):
	form_class = EmpleadoForm
	template_name = 'empleados/create_update_empleados.html'
	model = Empleado
	success_url='/empleados'

class CreateEmpleados(CreateView):
	form_class = EmpleadoForm
	template_name = 'empleados/create_empleado.html'
	model = Empleado
	success_url = '/empleados'

class EliminarView(DeleteView):
	model = Empleado
	template_name = 'empleados/eliminar_empleado.html'
	success_url='/empleados'


def write_pdf(template_src, context_dict):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = StringIO()
    pdf = pisa.pisaDocument(StringIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return http.HttpResponse(result.getvalue(), \
            content_type='application/pdf')
    return http.HttpResponse('Ocurrio un error al genera el reporte %s' % cgi.escape(html))


def generar_reporte_empleados(request):
	 empleados = Empleado.objects.all()

	 return write_pdf ('empleados/reporte_detalle_empleados.html',{'pagesize' : 'legal',
	 				   'empleados' : empleados})

templates/empleados/create_empleado.html
{% extends "base.html" %}
{% block title %}Personal{% endblock title %}

{% load bootstrap3 %}

{% block content %}

<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Personal
          </h1>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post" autocomplete="off">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div id="forms">
                                      {% bootstrap_form form %}
                                    </div>
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>             
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/empleados/create_update_empleados.html
{% extends "base.html" %}
{% block title %}Cliente{% endblock title %}

{% load bootstrap3 %}

{% block content %}
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Clientes
          </h1>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post" autocomplete="off">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div id="forms">
                                      {% bootstrap_form form %}
                                    </div>
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>             
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/empleados/detalle_empleados.html
{% extends "base.html" %}
{% block title %}Empleados{% endblock title %}
{% block content %}
<div class="wrapper"> 

  <div class="content-wrapper">

    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
          
            <div class="box-header with-border">
          		<a href="{% url 'empleados:lista_empleados' %}" class="btn btn-success">
            		<span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>              
              		<div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->            
            </div><!-- /.box-header -->
              <div class="box-body">
                  <table class="table table-striped table table-hover ">
                        <thead>
                            <tr>
                             <th><h2> Empleado: {{ object.empleado | capfirst }}</h2></th>           
                           </tr>
                        </thead>
	                    <tbody> 
	                          <tr class="success"> 
	                          	  <td><strong>Username:</strong></td>                           
	                              <td>{{ object.empleado | capfirst }}</td>
	                          </tr>
	                          <tr class="success">
	                          	  <td><strong>Nombre:</strong></td>
	                              <td>{{ user.first_name | capfirst}} </td> 
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Cedula:</strong></td>
	                              <td>{{ object.cedula |capfirst }}</td>                              
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Tipo:</strong> </td>
	                              <td>{{ object.tipo | capfirst}}</td>                  
	                           </tr>   
                             <tr class="success">
                                <td><strong>Habilitado:</strong> </td>
                                {% if object.habilitado == True %}
                                  <td>Si</td>                  
                                {% else %}
                                  <td>No</td>                  
                                {% endif %}
                             </tr>                         
	                    </tbody>
	               	</table>                                 
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/empleados/eliminar_empleado.html
{% extends "base.html" %}

{% block title %}Clientes{% endblock title %}
{% block content %}
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al cliente "{{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'clientes_app:lista_clientes' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/empleados/lista_empleados.html
{% extends "base.html" %}
{% block title %}Empleados{% endblock title %}

{% block css %}
<!-- DataTables -->
<link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
{% endblock css %}

{% block content %}
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Empleados
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title"><a href="{% url 'empleados:crear_empleado' %}" class="btn btn-success">
                      Nuevo Empleado
                    </a></h3>
                      {% if user.empleado.tipo == "Gerente" %}
                        <a  class="btn btn-primary pull-right" href="/empleados/reporte">imprimir</a>
                      {% endif %}
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Username</th>                       
                        <th>Nombre</th> 
                        <th>Cedula</th>                              
                        <th>Cargo</th>
                        <th>Acciones</th>                       
                      </tr>
                    </thead>
                    <tbody>
                    
                     {% for empleado in lista_empleados %}          

                        <tr> 
                          <td>{{ forloop.counter}}</td>
                          <td>{{ empleado.empleado | capfirst }}</td>
                          <td>{{ user.first_name | capfirst }} {{ user.last_name | capfirst}}</td> 
                          <td>{{ empleado.cedula }}</td>                              
                          <td>{{ empleado.tipo | capfirst }}</td>
                          <td class="text-right">
                                  <center><a href="{% url 'empleados:detalle_empleado' empleado.id %} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>

                                  <a href="{% url 'empleados:actualizar_empleado' empleado.id  %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                     {% if user.empleado.tipo == 'Gerente' %}
                                  <a href="{% url 'empleados:eliminar_empleado' empleado.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></center></a> 
                                   {% endif %}
                            </td>                      
                              
                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% endblock content %}

{% block extrajs %}
<!-- DataTables -->
<script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>

<!-- SlimScroll -->
<script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/plugins/fastclick/fastclick.min.js"></script>

    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
       </script>

       
{% endblock extrajs %}

templates/empleados/reporte_detalle_empleados.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <style >
        @page {
            size: landscape;
            @frame header_frame{
                -pdf-frame-content: headerContent;
                left: 5pt;
                top: 10pt;
                height: 100pt;
                }

            @frame content_frame {
                    left: 40pt; width: 760pt; top: 90pt; height: 460pt;
            }

            @frame footer {
                -pdf-frame-content: footerContent;
                bottom: 1cm;
                margin-left: 1cm;
                margin-right: 1cm;
                height: 0cm;
                }
        }
    </style>
</head>
<body>

<div id="headerContent">
    </br><center> <h2>REPORTE DE EMPLEADOS</h2></center>
    <center> <h3>USMOTOS</h3></center>
</div>

<div id="footerContent">
    Página: <pdf:pagenumber> de <pdf:pagecount>
</div>

<br>
<table style="border:2px solid black;border-collapse:collapse;">
    <tr>
        <th style="border:2px solid black; padding: 2px;">Nro</th>
        <th style="border:2px solid black; padding: 2px;">Cedula</th>
        <th style="border:2px solid black; padding: 2px;">Nombre</th>
        <th style="border:2px solid black; padding: 2px;">Cargo</th>        
        <th style="border:2px solid black; padding: 2px;">Celular</th>
        <th style="border:2px solid black; padding: 2px;">Habilitado</th>  


    </tr>
     {% for empleado in empleados %}
            
        <tr>
        <td width= 40 style="border:2px solid black; padding: 3px;">{{ forloop.counter }}</td>
         <td width= 80 style="border:2px solid black; padding: 3px;"><center>{{ empleado.cedula }}</center></td>
         <td width= 120 style="border:2px solid black; padding: 3px;"><center>{{ empleado.empleado.first_name |capfirst }} {{ empleado.empleado.last_name |capfirst }}</center></td>
         <td width=140 style="border:2px solid black; padding: 3px;"><center>{{ empleado.tipo}}</center></td>
         <td width= 80 style="border:2px solid black; padding: 3px;"><center>{{ empleado.celular }}</center></td>
         {% if empleado.habilitado == True %}
         	<td width= 70 style="border:2px solid black; padding: 3px;"><center>Si</center></td>
         {% else %}
         	<td width= 70 style="border:2px solid black; padding: 3px;"><center>No</center></td>
         {% endif %}
        </tr>         
              
    {% endfor %} 
    <td colspan="6" width= 70 style="border:2px solid black; padding: 3px;"><center>REPORTE EMPLEADOS USMOTOS</center></td>
  

</table>

<br />

</body>
</html>