apps/cliente/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaClientes, 
	DetalleView,
	ActualizarView,
	CreateClientes,
	EliminarView,
	generar_reporte_clientes
	)

urlpatterns = [

	url(r'^clientes/$', ListaClientes.as_view(), name = 'lista_clientes'),
	url(r'^clientes/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_cliente'),
	url(r'^clientes/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_cliente"),
	url(r'^clientes/agregar$', CreateClientes.as_view(), name='crear_cliente'),
	url(r'^clientes/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_cliente"), 
	url(r'^clientes/reporte/$', generar_reporte_clientes,name='reporte'),
	]

apps/proveedor/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaProveedores, 
	DetalleView,
	ActualizarView,
	CreateProveedores,
	EliminarView,
	generar_reporte_proveedores
	)

urlpatterns = [

	url(r'^proveedores/$', ListaProveedores.as_view(), name = 'lista_proveedores'),
	url(r'^proveedores/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_proveedor'),
	url(r'^proveedores/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_proveedor"),
	url(r'^proveedores/agregar$', CreateProveedores.as_view(), name='crear_proveedor'),
	url(r'^proveedores/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_proveedor"), 
	url(r'^proveedores/reporte/$', generar_reporte_proveedores,name='reporte'),
	]

sanbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings


# from apps.home.views import (
#     LandingView, HomeView,
#     ContactView, HelpView
#     )

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.inicio.urls',namespace='inicio')),
    
    url(r'^integrations/', include('apps.messenger.urls', namespace="integrations")),
    url(r'', include('apps.proveedor.urls',namespace='proveedor')),
    url(r'', include('apps.cliente.urls',namespace='clientes_app')),
    url(r'', include('apps.producto.urls',namespace='productos')),
    url(r'', include('apps.empleado.urls',namespace='empleados')),
    url(r'', include('apps.venta.urls',namespace='ventas')),
    url(r'', include('apps.repuesto.urls',namespace='repuestos')),
    url(r'', include('apps.propaganda.urls',namespace='propagandas')),


    # URL APPS PROJECT 

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),

]	

templates/proveedores/create_proveedores.html
{% extends "base.html" %}
{% block title %}Proveedor{% endblock title %}

{% load bootstrap3 %}

{% block content %}

<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Proveedor
          </h1>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post" autocomplete="off">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div id="forms">
                                      {% bootstrap_form form %}
                                    </div>
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>             
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/proveedores/create_update_proveedores.html
{% extends "base.html" %}
{% block title %}Proveedor{% endblock title %}

{% load bootstrap3 %}

{% block content %}

<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
         <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Proveedor
          </h1>
        </section>
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
             
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box-tools -->
                       
            </div><!-- /.box-header -->
              <div class="box-body"> 
    
                    <div class="row">
                      <div class="col-lg-12">
                        <form class="form-horizontal" method="post">
                          {% csrf_token %}
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <div id="forms">
                                      {% bootstrap_form form %}
                                    </div>
                                    <div class="pull-right" >
                                        <button type="submit" class="btn btn-sm btn-success m-r-5"><i class="fa fa-cog"></i> Guardar</button>
                                    </div>
                                </div>
                            </div>             
                        </form>
                      </div>
                    </div><!--/.row-->
            </div><!-- /.box body -->
          </div><!-- /.box info -->
          </div><!--col-->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/proveedores/detalle_proveedores.html
{% extends "base.html" %}

{% block title %}Proveedores{% endblock title %}

{% block content %}
<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
          
            <div class="box-header with-border">
          		<a href="{% url 'proveedor:lista_proveedores' %}" class="btn btn-success">
            		<span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>              
              		<div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->            
            </div><!-- /.box-header -->
              <div class="box-body">
                  <table class="table table-striped table table-hover ">
                        <thead>
                            <tr>
                             <th><h2> Proveedor: {{ object.nombre | capfirst }}</h2></th>           
                           </tr>
                        </thead>
	                    <tbody> 
	                          <tr class="success"> 
	                          	  <td><strong>Nombre:</strong></td>                           
	                              <td>{{ object.nombre | capfirst }}</td>
	                          </tr>
	                          <tr class="success">
	                          	  <td><strong>Direccion:</strong></td>
	                              <td>{{ object.direccion | capfirst}} </td> 
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Telefono:</strong></td>
	                              <td>{{ object.telefono |capfirst }}</td>                              
	                           </tr>
	                           	                           <tr class="success">
	                           	  <td><strong>Ciudad:</strong></td>
	                              <td>{{ object.ciudad | capfirst}}</td>                              
	                           </tr>
	                           <tr class="success">
	                           	  <td><strong>Email:</strong> </td>
	                              <td>{{ object.email }}</td>                  
	                           </tr>   
                             <tr class="success">
                                <td><strong>Habilitado:</strong> </td>
                                {% if object.habilitado == True %}
                                  <td>Si</td>                  
                                {% else %}
                                  <td>No</td>                  
                                {% endif %}
                             </tr>                         
	                    </tbody>
	               	</table>                                 
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/proveedores/eliminar_proveedor.html
{% extends "base.html" %}

{% block title %}Proveedores{% endblock title %}

{% block content %}

<div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
        <!-- Main content -->
    <section class="content">          
      <!-- START ALERTS AND CALLOUTS -->     
      <div class="row">
        <div class="col-md-12">
          <div class="box box-info">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>             
            </div><!-- /.box-header -->
              <div class="box-body">
                  <div class="callout callout-danger">                    
                    <h1> Eliminar</h1>
                    <form method="POST">
                    {% csrf_token %}
                      <p class="coloreliminar">¿Desea eliminar al Proveedor "{{ object.nombre }}?</p>
                      <input type="submit" value="Sí" class="btn btn-warning"> 
                      <a href="{% url 'clientes_app:lista_clientes' %}" class="btn btn-info">No</a>
                    </form>                        
                  </div>                                   
              </div><!-- /.box -->
          </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

{% endblock content %}

templates/proveedores/lista_proveedores.html
{% extends "base.html" %}

{% block title %}Proveedores{% endblock title %}

{% block css %}
<!-- DataTables -->
  <link rel="stylesheet" href="/static/plugins/datatables/dataTables.bootstrap.css">
{% endblock css %}

{% block content %}
    <div class="wrapper"> 
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>            
            Proveedores
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">

                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title"><a href="{% url 'proveedor:crear_proveedor' %}" class="btn btn-success">
                      Nuevo Proveedor
                    </a></h3>
                      {% if user.empleado.tipo == "Gerente" %}
                        <a  class="btn btn-primary pull-right" href="/proveedores/reporte">imprimir</a>
                      {% endif %}
                    <div class="box-tools pull-right">
                      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                  </div><!-- /.box-header -->
                  <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr>
                        <th>N°</th>
                        <th>Nombre</th>                       
                        <th>Direccion</th> 
                        <th>Telefono</th>                              
                        <th>Ciudad</th>
                        <th>Email</th>
                        <th>Acciones</th>                       
                      </tr>
                    </thead>
                    <tbody>
                    
                     {% for proveedor in lista_proveedores %}          

                        <tr> 
                          <td>{{ forloop.counter}}</td>
                          <td>{{ proveedor.nombre | capfirst }}</td>
                          <td>{{ proveedor.direccion | capfirst }}</td> 
                          <td>{{ proveedor.telefono }}</td>                              
                          <td>{{ proveedor.ciudad | capfirst }}</td>
                          <td>{{ proveedor.email }}</td>
                          <td class="text-right">
                                  <center><a href="{% url 'proveedor:detalle_proveedor' proveedor.id %} " class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>

                                  <a href="{% url 'proveedor:actualizar_proveedor' proveedor.id  %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                     {% if user.empleado.tipo == 'Gerente' %}
                                  <a href="{% url 'proveedor:eliminar_proveedor' proveedor.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></center></a> 
                                   {% endif %}
                            </td>                      
                              
                          </tr>
                      {% endfor %}
                    </tbody>

                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
{% endblock content %}

{% block extrajs %}
<!-- DataTables -->
<script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>

<!-- SlimScroll -->
<script src="/static/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/static/plugins/fastclick/fastclick.min.js"></script>

    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
       </script>

       
{% endblock extrajs %}

templates/proveedores/reporte_detalle_proveedores.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <style >
        @page {
            size: landscape;
            @frame header_frame{
                -pdf-frame-content: headerContent;
                left: 5pt;
                top: 10pt;
                height: 100pt;
                }

            @frame content_frame {
                    left: 40pt; width: 760pt; top: 90pt; height: 460pt;
            }

            @frame footer {
                -pdf-frame-content: footerContent;
                bottom: 1cm;
                margin-left: 1cm;
                margin-right: 1cm;
                height: 0cm;
                }
        }
    </style>
</head>
<body>

<div id="headerContent">
    </br><center> <h2>REPORTE DE PROVEEDORES</h2></center>
    <center> <h3>USMOTOS</h3></center>
</div>

<div id="footerContent">
    Página: <pdf:pagenumber> de <pdf:pagecount>
</div>

<br>
<table style="border:2px solid black;border-collapse:collapse;">
    <tr>
        <th style="border:2px solid black; padding: 2px;">Nro</th>
        <th style="border:2px solid black; padding: 2px;">Nombre</th>
        <th style="border:2px solid black; padding: 2px;">Direccion</th>
        <th style="border:2px solid black; padding: 2px;">Telefono</th>        
        <th style="border:2px solid black; padding: 2px;">Ciudad</th>
        <th style="border:2px solid black; padding: 2px;">Email</th>
        <th style="border:2px solid black; padding: 2px;">Habilitado</th>  


    </tr>
     {% for proveedor in proveedores %}
            
        <tr>
        <td width= 40 style="border:2px solid black; padding: 3px;">{{ forloop.counter }}</td>
         <td width= 80 style="border:2px solid black; padding: 3px;"><center>{{ proveedor.nombre }}</center></td>
         <td width= 220 style="border:2px solid black; padding: 3px;"><center>{{ proveedor.direccion }} </center></td>
         <td width=80 style="border:2px solid black; padding: 3px;"><center>{{ proveedor.telefono }}</center></td>
         <td width= 80 style="border:2px solid black; padding: 3px;"><center>{{ proveedor.ciudad }}</center></td>
         <td width= 140 style="border:2px solid black; padding: 3px;"><center>{{ proveedor.email }}</center></td>
         {% if proveedor.habilitado == True %}
         	<td width= 50 style="border:2px solid black; padding: 3px;"><center>Si</center></td>
         {% else %}
         	<td width= 50 style="border:2px solid black; padding: 3px;"><center>No</center></td>
         {% endif %}
        </tr>         
              
    {% endfor %} 
    <td colspan="6" width= 70 style="border:2px solid black; padding: 3px;"><center>REPORTE EMPLEADOS USMOTOS</center></td>
  

</table>

<br />

</body>
</html>