apps/cliente/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaClientes, 
	DetalleView,
	ActualizarView,
	CreateClientes,
	EliminarView,
	generar_reporte_clientes
	)

urlpatterns = [

	url(r'^clientes/$', ListaClientes.as_view(), name = 'lista_clientes'),
	url(r'^clientes/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_cliente'),
	url(r'^clientes/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_cliente"),
	url(r'^clientes/agregar$', CreateClientes.as_view(), name='crear_cliente'),
	url(r'^clientes/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_cliente"), 
	url(r'^clientes/reporte/$', generar_reporte_clientes,name='reporte'),
	]

apps/empleado/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from .views import (
	ListaEmpleados, 
	DetalleView,
	ActualizarView,
	CreateEmpleados,
	EliminarView,
	generar_reporte_empleados
	)

urlpatterns = [

	url(r'^empleados/$', ListaEmpleados.as_view(), name = 'lista_empleados'),
	url(r'^empleados/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_empleado'),
	url(r'^empleados/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_empleado"),
	url(r'^empleados/agregar$', CreateEmpleados.as_view(), name='crear_empleado'),
	url(r'^empleados/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_empleado"), 
	url(r'^empleados/reporte/$', generar_reporte_empleados,name='reporte'),
	]

apps/producto/urls.py
from django.conf.urls import url
from .views import (
	ListaProductos, 
	DetalleView,
	ActualizarView,
	CreateProductos,
	EliminarView,
	generar_reporte_productos,

	# inventario
	ProductoSucursalListView,
	ProductosListSucursal

)

urlpatterns = [

	url(r'^productos/$', ListaProductos.as_view(), name = 'lista_productos'),
	url(r'^productos/detalle/(?P<pk>\d+)/$', DetalleView.as_view(),name='detalle_productos'),
	url(r'^productos/actualizar/(?P<pk>\d+)/$', ActualizarView.as_view(), name ="actualizar_productos"),
	url(r'^productos/agregar$', CreateProductos.as_view(), name='crear_productos'),
	url(r'^productos/eliminar/(?P<pk>\d+)/$', EliminarView.as_view(), name="eliminar_productos"), 
	url(r'^productos/reporte/$', generar_reporte_productos,name='reporte'),

	url(r'^productos/sucursal/(?P<pk>\d+)/$', ProductoSucursalListView.as_view(), name='listar-productos-sucursal'),
	    
	url(r'^productos/inventario$', ProductosListSucursal.as_view(), name='listar-productos-inventario'),
	]

apps/venta/urls.py
from django.conf.urls import url
from .views import buscarCliente, buscarProducto,ventaCrear, ListaVentas,reporteventas

urlpatterns = (

    url(r'venta/lista_ventas/$', ListaVentas.as_view(), name = 'lista_ventas'),
    url(r'^venta/buscar_cliente/$', buscarCliente, name = "buscar_cliente"),
    url(r'^venta/buscar_producto/$', buscarProducto , name = "buscar_producto"),
   	url(r'^venta/productos/$', ventaCrear, name="venta_productos"),
    url(r'^factura/detalle/(?P<pk>\d+)/$', reporteventas , name="factura_venta_detalle"),
    
    # url(r'^factura/consultar$', 'apps.factura.views.consultarFactura', name="consultar_factura"),

    # url (r'factura/generar_reporte_factura/$', generar_pdf, name = 'generar_reporte_factura'),

    # url(r'factura/reporte_ventas/(?P<pk>\d+)/$', 'apps.factura.views.reporteventas', name='reporte_ventas'),

   )

sanbot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings


# from apps.home.views import (
#     LandingView, HomeView,
#     ContactView, HelpView
#     )

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.inicio.urls',namespace='inicio')),
    
    url(r'^integrations/', include('apps.messenger.urls', namespace="integrations")),
    url(r'', include('apps.proveedor.urls',namespace='proveedor')),
    url(r'', include('apps.cliente.urls',namespace='clientes_app')),
    url(r'', include('apps.producto.urls',namespace='productos')),
    url(r'', include('apps.empleado.urls',namespace='empleados')),
    url(r'', include('apps.venta.urls',namespace='ventas')),
    url(r'', include('apps.repuesto.urls',namespace='repuestos')),
    url(r'', include('apps.propaganda.urls',namespace='propagandas')),


    # URL APPS PROJECT 

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),

]	

templates/nav_empleados/gerente.html
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-child"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="{% url 'clientes_app:lista_clientes' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="{% url 'clientes_app:crear_cliente' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-users"></i> <span>Proveedores</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="{% url 'proveedor:lista_proveedores'%}"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="{% url 'proveedor:crear_proveedor' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-child"></i> <span>Personal</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="{% url 'empleados:lista_empleados' %}"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="{% url 'empleados:crear_empleado' %}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-motorcycle"></i>
                  <span>Productos</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="{% url 'productos:lista_productos' %}"><i class="fa fa fa-check-square"></i> Lista</a></li>                
                  <li><a href="{% url 'productos:crear_productos'%}"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>               
                </ul>
              </li>

       
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-wrench"></i>
                  <span>Asistencia</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa-circle-o"></i> Listado de Compras</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Realizar Compras</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Reportes Compras</a></li>                
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-tags"></i>
                  <span>Propaganda</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="{%url 'propagandas:lista_propagandas'%}"><i class="fa fa-circle-o"></i> Listado de Propagandas</a></li>
                  <li><a href="{% url 'propagandas:crear_propaganda' %}"><i class="fa fa-circle-o"></i> Crear Propaganda</a></li>                
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-laptop"></i>
                  <span>Ventas</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                <li>
                  <a href="{% url 'ventas:lista_ventas' %}"><i class="fa fa-circle-o"></i> Lista Ventas</a></li> 
                  <li><a href="{% url 'ventas:venta_productos'%}"><i class="fa fa-circle-o"></i> Realizar Venta</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Consultar Venta</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Reporte Venta</a></li>
                 
                </ul>
              </li>

templates/nav_empleados/mecanico.html
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-child"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="#"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="#"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-motorcycle"></i>
                  <span>Repuestos</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa fa-check-square"></i> Lista</a></li>                
                  <li><a href="#"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>               
                </ul>
              </li>

       
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-wrench"></i>
                  <span>Asistencia</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa-circle-o"></i> Listado de Compras</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Realizar Compras</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Reportes Compras</a></li>                
                </ul>
              </li>

templates/nav_empleados/vendedor.html
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-child"></i> <span>Clientes</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="#"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="#"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-wrench"></i> <span>Asistencia</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="#"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="#"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>
              <li class="treeview">
                <a href="#">
                  <i class="fa fa-tags"></i> <span>Promociones</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li class="active"><a href="#"><i class="fa fa-check-square"></i> Lista</a></li>
                  <li><a href="#"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-motorcycle"></i>
                  <span>Productos</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa fa-check-square"></i> Lista</a></li>                
                  <li><a href="#"><i class="fa fa-save"></i><small class="label pull-right bg-green">Nuevo</small>Nuevo</a></li>               
                </ul>
              </li>

              <li class="treeview">
                <a href="#">
                  <i class="fa fa-laptop"></i>
                  <span>Ventas</span>
                  <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Lista Ventas</a></li>
                 
                  <li><a href="#"><i class="fa fa-circle-o"></i> Realizar Venta</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Consultar Venta</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Reporte Venta</a></li>
                 
                </ul>
              </li>